import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import StyledComponentsRegistry from '@/lib/registry'
import RecoilRootProvider from '@/settings/recoilRootProvider'
import AuthSessionProvider from '@/component/auth/authSessionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <RecoilRootProvider>
            <AuthSessionProvider>{children}</AuthSessionProvider>
            </RecoilRootProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
